name: deploy on npmjs

on:
  push:
    tags:
    - /^v([0-9]+).([0-9]+).([0-9]+)$/

concurrency:
  group: ${{github.workflows}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: 'yarn'
      -
        name: Install
        run: yarn install --prefer-offline
      -
        name: publish on npmjs
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ NPM_TOKEN }}" > ~/.npmrc
          npm publish